# -*- coding: utf-8 -*-
"""Guitar Chord Tab to Piano Tab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-P3FnSAh9wSzRpB90AcBAkiTJQ7PbBPp
"""

!pip install python-docx -q

import re
import docx
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output
from google.colab import files

# ==========================================
# 1. THE CHORD ENGINE (Mathematical Voicing)
# ==========================================
def calculate_voicing(chord_str):
    """Calculates a 4-to-5 note piano voicing for ANY given chord string."""
    SVG_NOTES = ["C", "C#", "D", "Eb", "E", "F", "F#", "G", "G#", "A", "Bb", "B"]

    def get_note_index(note_name):
        mapping = {'C':0, 'C#':1, 'Db':1, 'D':2, 'D#':3, 'Eb':3, 'E':4, 'F':5,
                   'F#':6, 'Gb':6, 'G':7, 'G#':8, 'Ab':8, 'A':9, 'A#':10, 'Bb':10, 'B':11}
        return mapping.get(note_name, 0)

    # Clean the chord string: Remove anything inside parentheses for the calculation
    calc_chord = re.sub(r'\(.*?\)', '', chord_str)

    # A. Split slash chords
    parts = calc_chord.split('/')
    base_chord = parts[0]
    bass_note = parts[1] if len(parts) > 1 else None

    # B. Extract Root and Quality
    match = re.match(r"^([A-G][b#]?)(.*)", base_chord)
    if not match:
        return []

    root_note = match.group(1)
    quality = match.group(2).lower()
    root_idx = get_note_index(root_note)

    # C. Calculate Intervals (semitones from root)
    intervals = set([0]) # Always include Root

    if 'm' in quality and 'maj' not in quality:
        intervals.add(3)
    elif 'sus2' in quality:
        intervals.add(2)
    elif 'sus4' in quality or 'sus' in quality and 'sus2' not in quality:
        intervals.add(5)
    else:
        intervals.add(4)

    if 'maj7' in quality or 'maj9' in quality or 'maj13' in quality:
        intervals.add(11)
    elif '7' in quality or '9' in quality or '11' in quality or '13' in quality:
        intervals.add(10)
    elif 'dim7' in quality:
        intervals.add(9)

    if '9' in quality: intervals.add(14)
    if '13' in quality: intervals.add(21)
    if '6' in quality: intervals.add(9)
    if 'dim' in quality: intervals.add(6)
    if 'aug' in quality: intervals.add(8)

    if len(intervals) < 4 and 'dim' not in quality and 'aug' not in quality:
        intervals.add(7)

    # D. Map to actual note names
    note_names = [SVG_NOTES[(root_idx + iv) % 12] for iv in sorted(list(intervals))]

    # E. Build the Voicing (Assign Octaves)
    voicing = []
    actual_bass = bass_note if bass_note else root_note
    actual_bass_svg = SVG_NOTES[get_note_index(actual_bass)]

    voicing.append(f"{actual_bass_svg}2")

    notes_added = 0
    for note in note_names:
        if note != actual_bass_svg or len(voicing) == 0:
            octave = "3" if notes_added < 3 else "4"
            voicing.append(f"{note}{octave}")
            notes_added += 1

    return voicing

# ==========================================
# 2. UPLOAD AND EXTRACT
# ==========================================
print("Please upload your Word document (.docx):")
uploaded = files.upload()

if uploaded:
    filename = list(uploaded.keys())[0]
    doc = docx.Document(filename)
    sequence_data = []

    # Updated pattern to allow for parentheticals anywhere in the chord string
    chord_pattern = re.compile(r"^[A-G][#b]?(m|maj|min|M|sus|dim|aug|add)?[0-9]*(\(.*?\))?(sus[0-9]*)?(/[A-G][#b]?)?$", re.IGNORECASE)

    def is_chord_line(text):
        words = text.split()
        if not words: return False
        for word in words:
            clean_word = word.strip(".,;")
            if not chord_pattern.match(clean_word):
                return False
        return True

    paragraphs = [p.text.strip() for p in doc.paragraphs if p.text.strip()]

    for i, text in enumerate(paragraphs):
        if is_chord_line(text):
            chords_on_line = [w.strip(".,;") for w in text.split()]

            lyric_line = ""
            if i + 1 < len(paragraphs):
                next_text = paragraphs[i+1]
                if not is_chord_line(next_text) and not next_text.lower().startswith(("intro", "verse", "chorus", "bridge", "interlude", "musical")):
                    lyric_line = next_text

            for chord in chords_on_line:
                sequence_data.append({
                    "chord": chord,
                    "lyric": lyric_line,
                    "keys": calculate_voicing(chord)
                })

    print(f"\nSuccessfully extracted and calculated {len(sequence_data)} chords!")

    # ==========================================
    # 3. THE VISUALIZER UI
    # ==========================================
    class ColabPianoVisualizer:
        def __init__(self, sequence):
            self.song_sequence = sequence
            self.current_step = 0

            self.lyric_label = widgets.HTML()
            self.chord_label = widgets.HTML()

            self.prev_btn = widgets.Button(description="<< Previous")
            self.next_btn = widgets.Button(description="Next >>")

            self.prev_btn.on_click(self.prev_chord)
            self.next_btn.on_click(self.next_chord)

            self.controls = widgets.HBox([self.prev_btn, self.next_btn])
            self.piano_output = widgets.Output()

            display(self.lyric_label, self.chord_label, self.piano_output, self.controls)
            self.draw_piano()

        def draw_piano(self):
            self.update_display()

        def update_display(self):
            octaves = ["2", "3", "4"]
            white_notes = ["C", "D", "E", "F", "G", "A", "B"]
            black_notes = {"C#": 30, "Eb": 70, "F#": 150, "G#": 190, "Bb": 230}

            active_notes = []
            if self.song_sequence and 0 <= self.current_step < len(self.song_sequence):
                current_data = self.song_sequence[self.current_step]
                chord_name = current_data["chord"]
                lyric_text = current_data["lyric"]
                active_notes = current_data["keys"]

                self.lyric_label.value = f"<h3 style='color: #555; font-style: italic;'>{lyric_text if lyric_text else '...'}</h3>"
                self.chord_label.value = f"<h2 style='margin-top: 0;'>{chord_name} <span style='font-size: 14px; font-weight: normal; color: #888;'>({self.current_step + 1}/{len(self.song_sequence)})</span></h2>"
            else:
                self.lyric_label.value = ""
                self.chord_label.value = "<h2>Sequence Complete</h2>"

            svg = ['<svg width="840" height="150" style="border:1px solid #ccc; background:#fff;">']
            key_width = 40
            x_offset = 0

            white_key_elements = []
            black_key_elements = []

            for octave in octaves:
                octave_start_x = x_offset
                for note in white_notes:
                    full_note = note + octave
                    fill = "lightblue" if full_note in active_notes else "white"
                    white_key_elements.append(f'<rect x="{x_offset}" y="0" width="{key_width}" height="150" fill="{fill}" stroke="black" />')
                    x_offset += key_width

                for note, offset in black_notes.items():
                    full_note = note + octave
                    fill = "lightblue" if full_note in active_notes else "black"
                    bx = octave_start_x + offset
                    black_key_elements.append(f'<rect x="{bx}" y="0" width="{key_width * 0.6}" height="90" fill="{fill}" stroke="black" />')

            svg.extend(white_key_elements)
            svg.extend(black_key_elements)
            svg.append('</svg>')

            with self.piano_output:
                clear_output(wait=True)
                display(HTML("".join(svg)))

        def next_chord(self, b):
            if self.current_step < len(self.song_sequence) - 1:
                self.current_step += 1
                self.update_display()

        def prev_chord(self, b):
            if self.current_step > 0:
                self.current_step -= 1
                self.update_display()

    if sequence_data:
        app = ColabPianoVisualizer(sequence_data)
    else:
        print("No chords were found. Check the Word document format.")